import {defineConfig, globalIgnores} from 'eslint/config';
import eslint from '@eslint/js';
import globals from 'globals';
import stylistic from '@stylistic/eslint-plugin';
import tseslint from 'typescript-eslint';

export default defineConfig([
    globalIgnores([
        '.*/',
        'node_modules/',
        'dist/',
    ]),
    stylistic.configs.customize({
        indent: 4,
        quotes: 'single',
        jsx: true,
        semi: true,
        braceStyle: '1tbs',
    }),
    eslint.configs.recommended,
    tseslint.configs.recommendedTypeChecked,
    {languageOptions: {
        globals: globals.browser,
        parserOptions: {
            ecmaVersion: 2020,
            projectService: {
                allowDefaultProject: [
                    'eslint.config.mjs',
                ],
            },
        },
    }},
    {rules: {
        '@stylistic/array-bracket-spacing': 'error',
        '@stylistic/arrow-parens': ['error', 'always'],
        '@stylistic/arrow-spacing': 'error',
        '@stylistic/brace-style': 'error',
        '@stylistic/comma-dangle': ['error', 'always-multiline'],
        '@stylistic/comma-spacing': 'error',
        '@stylistic/comma-style': 'error',
        '@stylistic/computed-property-spacing': 'error',
        '@stylistic/eol-last': 'error',
        '@stylistic/function-call-spacing': 'error',
        '@stylistic/generator-star-spacing': ['error', 'after'],
        '@stylistic/implicit-arrow-linebreak': 'error',
        '@stylistic/jsx-child-element-spacing': 'error',
        '@stylistic/jsx-closing-bracket-location': 'error',
        '@stylistic/jsx-closing-tag-location': 'error',
        '@stylistic/jsx-curly-brace-presence': 'error',
        '@stylistic/jsx-curly-spacing': 'error',
        '@stylistic/jsx-equals-spacing': 'error',
        '@stylistic/jsx-quotes': ['error', 'prefer-double'],
        '@stylistic/jsx-self-closing-comp': 'error',
        '@stylistic/jsx-tag-spacing': 'error',
        '@stylistic/key-spacing': 'error',
        '@stylistic/keyword-spacing': 'error',
        '@stylistic/no-confusing-arrow': 'error',
        '@stylistic/no-extra-semi': 'error',
        '@stylistic/no-multi-spaces': ['error', {ignoreEOLComments: true}],
        '@stylistic/no-multiple-empty-lines': 'error',
        '@stylistic/no-trailing-spaces': 'error',
        '@stylistic/no-whitespace-before-property': 'error',
        '@stylistic/object-curly-spacing': ['error', 'never'],
        '@stylistic/padded-blocks': ['error', 'never'],
        '@stylistic/quote-props': 'off',
        '@stylistic/quotes': ['error', 'single'],
        '@stylistic/rest-spread-spacing': 'error',
        '@stylistic/semi': 'error',
        '@stylistic/semi-spacing': 'error',
        '@stylistic/semi-style': 'error',
        '@stylistic/space-before-function-paren': ['error', {anonymous: 'always', named: 'never', asyncArrow: 'always'}],
        '@stylistic/space-in-parens': ['error', 'never'],
        '@stylistic/space-infix-ops': 'error',
        '@stylistic/space-unary-ops': 'error',
        '@stylistic/spaced-comment': ['error', 'always', {markers: ['/']}],
        '@stylistic/switch-colon-spacing': 'error',
        '@stylistic/template-curly-spacing': 'error',
        '@stylistic/template-tag-spacing': 'error',
        '@stylistic/type-annotation-spacing': 'error',
        '@stylistic/yield-star-spacing': 'error',
        '@typescript-eslint/array-type': ['error', {'default': 'generic'}],
        '@typescript-eslint/no-explicit-any': 'off',
        '@typescript-eslint/no-misused-promises': 'off',
        '@typescript-eslint/no-unsafe-argument': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unsafe-return': 'off',
        '@typescript-eslint/no-unused-vars': ['error', {caughtErrors: 'none'}],
        '@typescript-eslint/require-await': 'off',
        '@typescript-eslint/triple-slash-reference': 'off',
        'arrow-body-style': ['error', 'as-needed'],
        'block-scoped-var': 'error',
        'camelcase': 'error',
        'consistent-return': 'error',
        'curly': ['error', 'all'],
        'eqeqeq': ['error', 'always', {'null': 'ignore'}],
        'func-style': ['error', 'declaration', {'allowArrowFunctions': true}],
        'max-len': ['error', {code: 120, ignoreStrings: true, ignoreTemplateLiterals: true}],
        'no-cond-assign': ['error', 'except-parens'],
        'no-duplicate-imports': 'error',
        'no-empty': ['error', {allowEmptyCatch: true}],
        'no-floating-decimal': 'error',
        'no-implicit-globals': 'error',
        'no-implied-eval': 'error',
        'no-mixed-operators': 'error',
        'no-multi-str': 'error',
        'no-return-assign': 'error',
        'no-return-await': 'off',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-undef': 'off',
        'no-unneeded-ternary': 'error',
        'no-unused-vars': 'off',
        'no-useless-return': 'error',
        'no-var': 'error',
        'operator-assignment': 'error',
        'prefer-arrow-callback': 'error',
        'prefer-const': ['error', {'destructuring': 'all'}],
        'prefer-destructuring': 'error',
        'prefer-numeric-literals': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'sort-imports': 'error',
        // 'sort-keys': ['error', 'asc', {minKeys: 10}],
        'unicode-bom': 'error',
        'yoda': 'error',
    }},
]);
