name: Deploy GH pages
on:
  push:
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'scripts/**'
      - 'src/related-parts-data.ts'
  pull_request:
    paths:
      - '.github/workflows/gh-pages.yml'
      - 'scripts/**'
      - 'src/related-parts-data.ts'
  schedule:
    - cron: '24 8 * * *'  # daily at 8:24 UTC
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Run build script
        run: python scripts/populate_data.py
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist
  deploy:
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
